Updates on Windows modules
aws/aws-eks-best-practices pull request #451
Opened 2024-01-05 19:31 UTC by marciogmorales

*Issue #, if available:*

*Description of changes:*

Updates on Hardening, License and Networking modules to match 2024 Amazon EKS Windows state.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2024-01-07 16:21 UTC, jicowan commented on content/windows/docs/hardening.md
> +Windows Server hardening involves identifying and remediating security vulnerabilities before they are exploited. Amazon EKS Optimized Windows AMIs are not hardened by default and only contain the la
The second sentence seems to contradict itself. They're not hardened but they container the latest security patches? Can you re-work this @marciogmorales?

2024-01-07 16:23 UTC, jicowan commented on content/windows/docs/hardening.md
> +Windows Server hardening involves identifying and remediating security vulnerabilities before they are exploited. Amazon EKS Optimized Windows AMIs are not hardened by default and only contain the la
I think a brief explanation of "hardening" in this context would help.

2024-01-07 16:24 UTC, jicowan commented on content/windows/docs/hardening.md
> +AWS provides customers with new Amazon EKS Optimized Windows AMIs every month, containing the latest Microsoft security patches, regardless of the Amazon EKS-supported version. As a best practice, Wi
Is this really true? Do customers who run Windows worker nodes replace their instances or do they patch or some combination of both?

2024-01-07 16:26 UTC, jicowan requested changes
Please update the paragraphs I had questions about @marciogmorales.

2024-01-08 14:35 UTC, marciogmorales commented
@jicowan Please, check updates.

2024-01-08 15:48 UTC, jicowan approved these changes

2024-01-08 16:29 UTC, merged